export default {
    FETCH_START : 'FETCH_START',
    FETCH_FAILED : "FETCH_FAILED",
    FETCH_SUCCEEDED : 'FETCH_SUCCEEDED',

    UI_FETCH_REQUESTED : "UI_FETCH_REQUESTED",
    UI_FETCH_LIST_SUCCEEDED : "UI_FETCH_LIST_SUCCEEDED",     //列表获取
    UI_FETCH_POST_SUCCEEDED : "UI_FETCH_POST_SUCCEEDED",    //文章获取

    AUTH_LOGIN_REQUESTED : "AUTH_LOGIN_REQUESTED",
    AUTH_LOGIN_SUCCESS : "AUTH_LOGIN_SUCCESS",
    AUTH_LOGOUT : "AUTH_LOGOUT",

    FORM_VALUE_ONCHANGE : "FORM_VALUE_ONCHANGE",
    FORM_TOGGLE_EDITING : "FORM_TOGGLE_EDITING",
}