export default {
    FETCH_FAILED : "FETCH_FAILED",
    FETCH_REQUESTED : "FETCH_REQUESTED",
    FETCH_SUCCEEDED : 'FETCH_SUCCEEDED',
    FETCH_START : 'FETCH_START',
    FETCH_LIST_SUCCEEDED : "FETCH_LIST_SUCCEEDED",     //列表获取
    FETCH_POST_SUCCEEDED : "FETCH_POST_SUCCEEDED",    //文章获取
    // FETCH_AUTHOR_SUCCEEDED : "FETCH_AUTHOR_SUCCEEDED" //作者获取
}